server: 
  port: 8010

spring:
  application:
    name: animal

  jpa:
    hibernate:
      ddl-auto: update

    config:
    import: optional:configserver:http//configserver:8888

commentary:
  service:
    url: http://localhost:8030
