#######GATEWAY CONFIGURATION#####

# spring:
#   config:
#     import: "optional:configserver:"

#   application:
#     name: gateway
    
#   cloud:
#     config:
#       uri: http://localhost:8888


######CONSUL CONFIGURATION######
server:
  port: 8822

spring:
  config:
    import: optional:configserver:http://configserver:8888

  application:
    name: gateway

  cloud:
    consul:
      host: consul
      port: 8500 
      discovery:
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${server.port} 

    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user
              predicates:
                - Path=/api/v1/auth/**,/api/v1/user/**           

