FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar Vet&CoApp.jar
EXPOSE 8888
ENTRYPOINT ["java", "-jar", "Vet&CoApp.jar"]