#####Appointment Service Configuration#####
server:
  port: 8040

spring:
  application:
    name: appointment

  jpa:
    hibernate:
      ddl-auto: update

    config:
    import: optional:configserver:http://configserver:8888

commentary:
  service:
    url: http://commentary-service:8083
