package com.onist.appointment.model;

public enum Reason {
    SUIVI_DE_ROUTINE,
    CHIRURGIE,
    ODONTOLOGIE,
    CONSULTATION_POUR_SYMPTOME,
    EXAMENS_COMPLEMENTAIRES,
    URGENCES,
    REPRODUCTION_MATERNITE,
    ADMINISTRATIF,
    GERIATRIE_FIN_DE_VIE,
    TELECONSULTATION
}
