server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # The server does not register itself/Le serveur ne s'enregistre pas lui-même
    fetch-registry: false         # It does not retrieve the register/Il ne récupère pas le registre
  server:
    enable-self-preservation: false  # Avoid warnings/Evite les warnings